#ifndef BOARD_BUTTONSCONTROLLER_CONFIG_H
#define BOARD_BUTTONSCONTROLLER_CONFIG_H

/**
 * Do NOT edit this file!
 *
 * This is the default ButtonsController config file.
 * You may provide your own implementation at project level.
 *
 * For this:
 * - Copy/paste this file into a folder named 'config' in
 *   you projects include/source directory.
 * - Add a compiler include path so that your file is seen
 *   before the default config file provided in the platform
 *   package.
 * - Adjust the content of your config file to your needs.
 * - Remove this comment in your config file.
 */

#include "main.h"       // To get GPIO user labels (BUTTON0, BUTTON1, etc.)

#define BUTTONSCONTROLLER_EXCLUDE_FROM_BUILD        0       /* Default: 0 */
#define TRACE_BUTTONSCONTROLLER_NOTIFICATIONS       0

#endif // BOARD_BUTTONSCONTROLLER_CONFIG_H
